### ISSUE TITLE
feat(Support multiple authors) in front matter and templates

### ISSUE THREAD

**Issue by diniremix** [micahkepe/radion#30]
**Is your feature request related to a problem? Please describe.**
Currently, posts only support a single author via front matter (`author = "Anne"`), I’d like to credit multiple authors cleanly in a post.

**Describe the solution you'd like**
Allow setting multiple authors in the front matter using an array, like this:

```toml
# in a some post
[extra]
authors = ["John", "Anne", "Adam"]
```

**Describe alternatives you've considered**
I'm currently using a workaround with a naive template implementation:

```jinja2
{% if page.extra.authors %}
    {% set total = page.extra.authors | length %}
    Published by
    {% for author in page.extra.authors %}
        {% if loop.last and total > 1 %}
            and {{ author }}
        {% elif loop.index0 == 0 %}
            {{ author }}
        {% else %}
            , {{ author }}
        {% endif %}
    {% endfor %}
{% elif config.extra.author %}
    Published by {{ config.extra.author }}
{% endif %}
```

**Additional context**
This is especially useful for guest contributors :smile:

**Comment by micahkepe** [comment]
Hello! Yes this should be relatively simple to support. Zola already supports having an authors array in the frontmatter (before the [extra] section: https://www.getzola.org/documentation/content/page/#front-matter

The authors variable is then exposed as a page variable: https://www.getzola.org/documentation/templates/pages-sections/#page-variables

I can work on a solution later today.

**Comment by micahkepe** [comment]
Multiple authors are now supported. Here are the update instructions for author attribution:

You may define the author(s) of a page in either the root `config.toml` file, or
on a per-page basis in the page's frontmatter.

The order of precedence for determining the author shown in a page’s footer is:

1. `page.extra.author` (highest precedence)
2. `page.authors`
3. `page.config.author` (lowest precedence, default)

#### Defining a Global Default Author in `config.toml`

In `config.toml`:

```toml
[extra]
author = "John Smith"
```

#### Defining Author(s) Per-Page

At the top of a page in its frontmatter (wrap this in `+++`):

1. Define a single author for the page:

```toml
title = "..."
date = 1970-01-01

[extra]
author = "John Smith"
```

Alternatively, you can define the `page.authors` variable with a single entry:

```toml
title = "..."
date = 1970-01-01
authors = ["John Smith"]
```

2. Define multiple authors for a page:

```toml
title = "..."
date = 1970-01-01
authors = ["John Smith", "Joe Schmoe", "Jane Doe"]
```

> [!NOTE]
> Do not define both `extra.author` and `authors` in the same page unless you
> want `extra.author` to take precedence.


You can also view these configuration instructions on the live site here: https://micahkepe.com/radion/configuration/#author-attribution
